#!/bin/bash
get_ts_from_list()
{
	grep -v "^#" <<< "$1" | while read; do
	if [ "${REPLY:0:1}" = "/" ]; then
		URL_SCHEMA="${URL%%://*}"
		URL_WO_SCHEMA="${URL#$URL_SCHEMA://}"
		URL_HOST="${URL_WO_SCHEMA%%/*}"
		echo "$URL_SCHEMA://$URL_HOST$REPLY"
	elif [ "${REPLY:0:4}" != "http" ]; then
		URL_BASE="${URL%%\?*}"
		echo "${URL_BASE%/*}/$REPLY"
	else
		echo "$REPLY"
	fi
	done | wget -T 30 -t 0 -q -i -
}

SED=gsed
if ! which $SED > /dev/null; then
	SED=sed
fi
CURL_W_OPT="curl --retry 3 -m 3 -s"

DURATION=1
OUTDIR=out
while [ -n "$1" -a "${1:0:1}" = "-" ]; do
	if [ "$1" = "-t" ]; then
		DURATION=$2
		shift 2
	elif [ "$1" = "-d" ]; then
		OUTDIR=$2
		shift 2
	fi
done
if [ -z "$1" ]; then
	echo "Usage: $0 [-t duration] [-d directory] m3u8_url"
	exit
fi
INDEX="$($CURL_W_OPT "$1")"
URL="$1"
LIST=
if [ -z "$INDEX" -a -n "$URL" -a ${#URL} -le 2 ]; then
	URL="$(xxd -ps -c 70 -r <<< 687474703a2f2f76646e2e6c6976652e636e74762e636e2f617069322f6c69766548746d6c352e646f3f6368616e6e656c3d70613a2f2f636374765f7032705f686463637476)$URL&client=html5"
	URL="${URL/cctvah/anhui}"
	echo "$URL"
	INDEX="$($CURL_W_OPT "$URL")"
fi
if [ -n "$INDEX" -a "${INDEX:0:18}" = "var html5VideoData" ]; then
	URL="${INDEX#*\"hls2\":\"}"
	if [ "$URL" != "$INDEX" ]; then
		echo "Resolving html5VideoData"
		URL="${URL%%\"*}"
		URL="$($SED 's/wscdns.com/cloudcdn.net/' <<< "$URL")"
		INDEX="$($CURL_W_OPT "$URL")"
		echo "$URL"
	fi
fi
if [ -n "$INDEX" -a "${INDEX:0:7}" = "#EXTM3U" ]; then
	if grep -q "#EXT-X-STREAM-INF" <<< "$INDEX"; then
		INDEX="$(tr -d '\r' <<< "$INDEX" | $SED -n '/^#EXT-X-STREAM-INF/,/^[^#]/{/^#/H;/^[^#]/{G;s/\n/ /g;s/BANDWIDTH=/& /;p;s/.*//;h}}' | sort -n -k 3 -r)"
		while read M3U8 _; do
			if [ "${M3U8:0:1}" = "/" ]; then
				URL_SCHEMA="${URL%%://*}"
				URL_WO_SCHEMA="${URL#$URL_SCHEMA://}"
				URL_HOST="${URL_WO_SCHEMA%%/*}"
				M3U8="$URL_SCHEMA://$URL_HOST$M3U8"
			elif [ "${M3U8:0:4}" != "http" ]; then
				URL_BASE="${URL%%\?*}"
				M3U8="${URL_BASE%/*}/$M3U8"
			fi
			echo "Trying $M3U8"
			LIST="$($CURL_W_OPT "$M3U8")"
			if [ -n "$LIST" -a "${LIST:0:7}" = "#EXTM3U" ]; then
				URL="$M3U8"
				echo "Selected $M3U8"
				break
			fi
		done <<< "$INDEX"
	else
		LIST="$INDEX"
	fi
else
	echo "Invalid source $1"
	exit 1
fi
LIST="$(tr -d '\r' <<< "$LIST")"
STEP=1
if grep -q "#EXT-X-TARGETDURATION" <<< "$LIST"; then
	STEP="$($SED -n '/^#EXT-X-TARGETDURATION/{s/^.*: *//;p}' <<< "$LIST")"
	if [ "$STEP" -gt 2 ]; then
		STEP=$(($STEP - 1))
	else
		STEP=1
	fi
fi
echo "Duration $DURATION, step $STEP"
mkdir -p "$OUTDIR"
cd "$OUTDIR"
if grep -q "#EXT-X-MEDIA-SEQUENCE" <<< "$LIST"; then
	LASTN="$($SED -n '/^#EXT-X-MEDIA-SEQUENCE/{s/^.*: *//;p}' <<< "$LIST")"
	OLDLIST=
	while [ "$DURATION" -gt 0 ]; do
		THIS_STEP="${LIST#*#EXTINF:}"
		if [ "$THIS_STEP" != "$LIST" ]; then
			THIS_STEP=$($SED -n '1{s/,.*//;p}' <<< "$THIS_STEP")
			if [ "$THIS_STEP" -gt 2 ]; then
				THIS_STEP=$(($THIS_STEP - 1))
			else
				THIS_STEP=1
			fi
		else
			THIS_STEP=
		fi
		echo "Downloading sequence $LASTN, left duration $DURATION, step ${THIS_STEP:-$STEP}"
		get_ts_from_list "$(diff <(cat <<< "$OLDLIST") <(cat <<< "$LIST") | $SED -n '/^> /{s/^> //;p}')"
		OLDLIST="$LIST"
		DURATION=$(($DURATION - ${THIS_STEP:-$STEP}))
		LIST="$($CURL_W_OPT "$URL" | tr -d '\r')"
		N="$($SED -n '/^#EXT-X-MEDIA-SEQUENCE/{s/^.*: *//;p}' <<< "$LIST" | head -1)"
		while [ "$N" = "$LASTN" -o -z "$N" -o "0$N" -le "0$LASTN" ]; do
			sleep 1
			LIST="$($CURL_W_OPT "$URL" | tr -d '\r')"
			N="$($SED -n '/^#EXT-X-MEDIA-SEQUENCE/{s/^.*: *//;p}' <<< "$LIST")"
		done
		LASTN="$N"
	done
else
	echo "No sequence. Download only once."
	get_ts_from_list "$LIST"
fi
