#!/bin/bash
FIFO="$HOME/.mplayer/fifo"
INPUTCONF="$HOME/.mplayer/input.conf"
FNAMEFILE="$HOME/.mplayer/filename"
STREAMPOS="$HOME/.mplayer/stream_pos"
TAGFILE="$HOME/.mov"

if [ "$1" = "-do" ]; then
	echo "pausing_keep_force run \"echo \\\"\${filename}\\\" > $FNAMEFILE\"" > "$FIFO"
	while true; do
		FNAME="$(cat "$FNAMEFILE" 2>/dev/null)"
		if [ $? -eq 0 ]; then
			rm "$FNAMEFILE"
			break
		fi
		sleep 0.05
	done
	echo "pausing_keep_force run \"echo \${stream_pos} > $STREAMPOS\"" > "$FIFO"
	while true; do
		SPOS="$(cat "$STREAMPOS" 2>/dev/null)"
		if [ $? -eq 0 ]; then
			rm "$STREAMPOS"
			break
		fi
		sleep 0.05
	done
	TAGS="$(zenity --entry --text="$FNAME @$SPOS")"
	S=
	for T in $TAGS; do
		S="$S	$T"
	done
	if [ -n "$S" ]; then
		echo "$FNAME$S" >> $TAGFILE
	fi
	exit
fi
rm -f "$FNAMEFILE"
rm -f "$STREAMPOS"

if mkdir -p "$HOME/.mplayer"; then
	:
else
	echo "Cannot make directory $HOME/.mplayer"
	exit 1
fi
if [ ! -p "$FIFO" ]; then
	rm -f "$FIFO"
	mkfifo "$FIFO"
fi
if grep -w mov "$INPUTCONF" > /dev/null 2>&1; then
	:
else
	echo "Ctrl+m run \"mov -do\"" >> "$INPUTCONF"
fi
mplayer -slave -quiet -input "file=$HOME/.mplayer/fifo" "$@"
